Repository StackStorm/packer-st2, pull requests merged in 2018-05, with the labels that each got.

#12 Authorize Vagrant SSH key-based access
  Vagrantfile
  scripts/vagrant.sh
  st2.json
Labels: RFR, enhancement

#16 Add system InSpec tests
  CHANGELOG.md
  README.md
  opt/README.md
  opt/test
  scripts/post_cleanup.sh
  scripts/pre_cleanup.sh
  scripts/test.sh
  scripts/vagrant.sh
  st2.json
  test/README.md
  test/integration/1-system/controls/packages_test.rb
  test/integration/1-system/controls/services_test.rb
  test/integration/1-system/controls/settings_test.rb
  test/integration/1-system/controls/vagrant_test.rb
  test/integration/1-system/inspec.lock
  test/integration/1-system/inspec.yml
Labels: RFR, tests

#18 Add MOTD/Welcome message after console login
  CHANGELOG.md
  scripts/welcome.sh
  st2.json
  test/integration/1-system/controls/motd-welcome_test.rb
Labels: RFR, feature

#20 Add StackStorm integration tests
  CHANGELOG.md
  README.md
  opt/bin/st2-integration-tests
  scripts/st2-integration-tests.sh
  scripts/test.sh
  test/integration/2-stackstorm/controls/mongodb_test.rb
  test/integration/2-stackstorm/controls/rabbitmq_test.rb
  test/integration/2-stackstorm/controls/repository_test.rb
  test/integration/2-stackstorm/controls/services_test.rb
  test/integration/2-stackstorm/controls/st2-actions_test.rb
  test/integration/2-stackstorm/controls/st2_test.rb
  test/integration/2-stackstorm/controls/st2chatops_test.rb
  test/integration/2-stackstorm/controls/st2web_test.rb
  test/integration/2-stackstorm/controls/stanley_test.rb
  test/integration/2-stackstorm/inspec.lock
  test/integration/2-stackstorm/inspec.yml
Labels: RFR, documentation, feature, tests

#22 Add virtualbox guest additions
  CHANGELOG.md
  scripts/virtualbox.sh
  st2.json
  test/integration/1-system/controls/virtualbox_test.rb
Labels: RFR, Virtualbox, feature

#23 Getting the initial demo release out
  CHANGELOG.md
  README.md
  st2.json
Labels: RFR

#19 Add CI
  .circleci/ansible/bin/install_dependencies.sh
  .circleci/ansible/create.yml
  .circleci/ansible/destroy.yml
  .circleci/ansible/provision.yml
  .circleci/bin/build.py
  .circleci/bin/scrap-metal
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  README.md
  scripts/reboot.sh
  st2.json
Labels: CI/CD, WIP, feature

#25 Deploy artifacts to github releases
  .circleci/config.yml
  CHANGELOG.md
  builds/README.md
Labels: CI/CD, WIP, feature

#26 Set 'st2_version' and 'box_version' dynamically or use env vars
  CHANGELOG.md
  Makefile
  README.md
  st2.json
Labels: RFR, enhancement

#27 Add `st2_deploy` build step to upload the box to Vagrant Cloud
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  st2.json
  st2_deploy.json
Labels: CI/CD, RFR, feature

#31 Fix Vagrant Cloud Deploy 'file not exist' error
  CHANGELOG.md
  Makefile
Labels: RFR, bug

#29 Expose st2web in Vagrant
  CHANGELOG.md
  Vagrantfile
  Vagrantfile.template
Labels: RFR, Vagrant, enhancement

#33 Extract ST2_VERSION and BOX_VERSION from the release tags
  .circleci/bin/build.py
  .circleci/config.yml
  CHANGELOG.md
Labels: CI/CD, RFR, enhancement

#35 Fix version pinning message not showing properly in CircleCI
  .circleci/config.yml
Labels: RFR, bug

#36 Add fallback port forwarding rule for accessing st2web
  CHANGELOG.md
  Vagrantfile.template
Labels: enhancement
